# using Plots

# include variables and function definitions

include("./gaussianbeam.jl")

# discrete model for continuous grin lens

l = 1e-5        # width of the liquid slices (m)
λ = λ2          # wavelength (m)
P = 1           # power of laser (W)
k = 0.6         # water thermic diffusion coefficient (W/m/K)
α = 8           # water absorption coefficient (1/m)
dndT = -1e-4    # index variation coefficient (1/K)

focale(l,w) = π * k * w^2 / ( α * P * l * dndT)  # thermally induced focal length of liquid slice

z0 = 1e-2 # initial position of the waist without lens effect (m)
w0 = 6.5e-6 # initial waist of the beam (m)

steps = 0:l:4e-2                # position along the tank to compute on
focal = zeros(length(steps))    # focal length of liquid slice lens
shift = zeros(length(steps))    # focal shift generated by liquid slice lens
magnif = zeros(length(steps))   # magnification for liquid slice lens
pos = zeros(length(steps))      # position of the waist after liquid slice lens
waist = zeros(length(steps))    # size of the waist after liqud slice lens

for (i,z) in enumerate(steps)
    global z0, w0, focal, shift, magnif, pos, waist
    
    # compute lens effect
    sa = z0 - z                         # algebric distance lens-object
    w0a = w0                            # waist before lens
    zra = rayleigh_length(w0a, λ)       # Rayleigh length before lens
    wa = gaussian_width(sa, w0a, λ)     # beam width at lens position
    fprime = focale(l, wa)              # thermally induced focal length
    sb = sprime(sa, fprime, zra)        # algebric distance lens-image
    mag = magnification(sa, fprime, zra)
    w0b = w0a * mag                     # waist after lens

    # update beam properties
    z0 = z + sb                         # update z0 with new absolute beam position
    w0 = w0b                            # update w0 with new beam waist

    # update tables to take it into account
    focal[i] = zra/fprime
    shift[i] = sb-sa
    magnif[i] = mag
    pos[i] = z0
    waist[i] = w0
end